# Generated by Django 5.0.7 on 2024-08-14 10:46

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='innovators')
    Group.objects.get_or_create(name='partners')
    Group.objects.get_or_create(name='advisors')
    Group.objects.get_or_create(name='challengers')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
