# Generated by Django 5.0.7 on 2024-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_innovatorprofile_availability_innovatorprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorprofile',
            name='address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovatorprofile',
            name='address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
