# Generated by Django 5.0.7 on 2024-08-20 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0002_projectimage_project_main_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillrequired',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='accepted_users',
            field=models.ManyToManyField(blank=True, related_name='accepted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='project_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillrequired',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.skill'),
            preserve_default=False,
        ),
    ]
